
all:

OPENFST_CXXFLAGS = 
OPENFST_LDLIBS = 
include ../kaldi.mk

OBJFILES = ivector-extractor.o 

LIBNAME = kaldi-ivector2

ADDLIBS = ../gmm/kaldi-gmm.a ../matrix/kaldi-matrix.a ../base/kaldi-base.a \
        ../util/kaldi-util.a 

include ../makefiles/default_rules.mk
